const tag = [
    { name: 'XIUREN', link: 'https://mrcong.com/tag/xiuren/' },
    { name: 'UGIRLS', link: 'https://mrcong.com/tag/ugirls/' },
    { name: 'LegBaby', link: 'https://mrcong.com/tag/legbaby/' },
    { name: 'TuiGirl', link: 'https://mrcong.com/tag/tuigirl/' },
    { name: 'BoLoli', link: 'https://mrcong.com/tag/bololi/' },
    { name: 'MiStar', link: 'https://mrcong.com/tag/mistar/' },
    { name: 'FEILIN', link: 'https://mrcong.com/tag/feilin/' },
    { name: 'MFStar', link: 'https://mrcong.com/tag/mfstar/' },
    { name: 'UXING', link: 'https://mrcong.com/tag/uxing/' },
    { name: 'WingS', link: 'https://mrcong.com/tag/wings/' },
    { name: 'IMISS', link: 'https://mrcong.com/tag/imiss/' },
    { name: 'MyGirl', link: 'https://mrcong.com/tag/mygirl/' },
    { name: 'MiiTao', link: 'https://mrcong.com/tag/miitao/' },
    { name: 'YouWu', link: 'https://mrcong.com/tag/youwu/' },
    { name: 'TASTE', link: 'https://mrcong.com/tag/taste/' },
    { name: 'LeYuan', link: 'https://mrcong.com/tag/leyuan/' },
    { name: 'HuaYan', link: 'https://mrcong.com/tag/huayan/' },
    { name: 'Tukmo', link: 'https://mrcong.com/tag/tukmo/' },
    { name: 'Kimoe', link: 'https://mrcong.com/tag/kimoe/' },
    { name: 'TouTiao', link: 'https://mrcong.com/tag/toutiao/' },
    { name: 'TGOD', link: 'https://mrcong.com/tag/tgod/' },
    { name: 'QingDouKe', link: 'https://mrcong.com/tag/qingdouke/' },
    { name: 'CANDY', link: 'https://mrcong.com/tag/candy/' },
    { name: 'DKGirl', link: 'https://mrcong.com/tag/dkgirl/' },
    { name: 'YouMi', link: 'https://mrcong.com/tag/youmi/' },
    { name: 'MintYe', link: 'https://mrcong.com/tag/mintye/' },
    { name: 'KelaGirls', link: 'https://mrcong.com/tag/kelagirls/' },
    { name: 'MF', link: 'https://mrcong.com/tag/mf/' },
    { name: 'ISHOW', link: 'https://mrcong.com/tag/ishow/' },
    { name: 'FToow', link: 'https://mrcong.com/tag/ftoow/' },
    { name: 'Djawa', link: 'https://mrcong.com/tag/djawa/' },
    { name: 'Home', link: 'https://mrcong.com/' }
  ]
  
const minimal_args = [
    '--autoplay-policy=user-gesture-required',
    '--disable-background-networking',
    '--disable-background-timer-throttling',
    '--disable-backgrounding-occluded-windows',
    '--disable-breakpad',
    '--disable-client-side-phishing-detection',
    '--disable-component-update',
    '--disable-default-apps',
    '--disable-dev-shm-usage',
    '--disable-domain-reliability',
    '--disable-extensions',
    '--disable-features=AudioServiceOutOfProcess',
    '--disable-hang-monitor',
    '--disable-ipc-flooding-protection',
    '--disable-notifications',
    '--disable-offer-store-unmasked-wallet-cards',
    '--disable-popup-blocking',
    '--disable-print-preview',
    '--disable-prompt-on-repost',
    '--disable-renderer-backgrounding',
    '--disable-setuid-sandbox',
    '--disable-speech-api',
    '--disable-sync',
    '--hide-scrollbars',
    '--ignore-gpu-blacklist',
    '--metrics-recording-only',
    '--mute-audio',
    '--no-default-browser-check',
    '--no-first-run',
    '--no-pings',
    '--no-sandbox',
    '--no-zygote',
    '--password-store=basic',
    '--use-gl=swiftshader',
    '--use-mock-keychain',
];

module.exports = { tag, minimal_args }
